name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [14, 16, 18]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: npm i
      - run: npm run check-format
      - run: npm run lint
      - run: npm run build
      - run: npm run test
      - run: npm run docs
      - name: Deploy docs to GitHub Pages
        # only on version tags like v3.0.0
        if: ${{ matrix.node == '18' && github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v') }}
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages
          folder: docs
          clean: true
